### ISSUE TITLE
account warning points get out of sync

### ISSUE THREAD

**Issue by Xon** [Xon/XenForo-WarningImprovements#26]
Account warning points get out of sync if you issue a warning which expires in 0 time.

**Comment by Firnagzen** [comment]
Spent two hours fifteen minutes hunting this bug, turns out to be a XenForo base error.Temporary fix commited: [ref](https://github.com/Xon/XenForo-WarningImprovements/commit/781676ee96dd9849c7dcfbf499cef35fcc6a8381)

Bug report made to XenForo [here](https://xenforo.com/community/threads/infractions-with-0-time-result-in-a-mismatch-between-infractions-and-profile-points.128917/).
